name: Output Issues Metadata

on:
  issues:
    types: [opened]

defaults:
  run:
    working-directory: './02-workflows-and-events'

jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: Output Issue Metadata
        run: |
          echo "Issue Number: ${{ github.event.issue.number }}"
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Body: ${{ github.event.issue.body }}"
      