name: Load and cache dependencies
description: Load and cache dependencies from package-lock.json
runs:
  using: composite
  steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v4
      with:
        path: 05-custom-actions/node_modules
        key: ${{ runner.os }}-node-05-${{ hashFiles('05-custom-actions/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-05-
      
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      working-directory: ./05-custom-actions
      run: npm ci
      shell: bash