name: Reusable Deploy workflow
on:
  workflow_call:
    inputs:
      deploy-dir:
        description: The name of the directory to deploy
        required: false
        default: dist
        type: string
    
    outputs:
      result:
        description: The result of the deploy
        value: ${{ jobs.deploy.outputs.outcome }}

jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v4
        with: 
          name: ${{ inputs.deploy-dir }}
      
      - name: List files
        run: ls
      
      - name: Deploy
        run: echo "Deploying from reusable workflow..."

      - name: Set result output
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT
      
